# Generated by Django 6.0.4 on 2026-05-25 16:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('ville', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hotels_photos/')),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('equipements', models.TextField(help_text='Comma-separated values (e.g. WiFi, Piscine, Parking)')),
            ],
        ),
        migrations.CreateModel(
            name='TypeChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='e.g. Single, Double, Suite Presidentielle', max_length=100)),
                ('capacite_personnes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chambre', models.CharField(max_length=20)),
                ('prix_base_nuit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('est_active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='reservations.hotel')),
                ('type_chambre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chambres', to='reservations.typechambre')),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='reservations.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrivee', models.DateField()),
                ('date_depart', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut_paiement', models.CharField(choices=[('En attente', 'En attente'), ('Confirmee', 'Confirmée'), ('Annulee', 'Annulée')], default='En attente', max_length=20)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.chambre')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('est_disponible', models.BooleanField(default=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='reservations.chambre')),
            ],
            options={
                'unique_together': {('chambre', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prix_applique', models.DecimalField(decimal_places=2, help_text='Dynamic price after algorithm adjustment', max_digits=10)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_specifiques', to='reservations.chambre')),
            ],
            options={
                'unique_together': {('chambre', 'date')},
            },
        ),
    ]
