# Generated by Django 6.0.5 on 2026-05-31 16:24

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='stripe_charge_id',
            new_name='stripe_intent_id',
        ),
        migrations.AlterUniqueTogether(
            name='disponibilite',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tarif',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='avis',
            name='client',
        ),
        migrations.RemoveField(
            model_name='avis',
            name='date_publication',
        ),
        migrations.RemoveField(
            model_name='chambre',
            name='est_active',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='client',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='prix_total',
        ),
        migrations.RemoveField(
            model_name='typechambre',
            name='capacite_personnes',
        ),
        migrations.RemoveField(
            model_name='typechambre',
            name='description',
        ),
        migrations.AddField(
            model_name='avis',
            name='auteur',
            field=models.CharField(default='Anonyme', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='nom_client',
            field=models.CharField(default='Client Inconnu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarif',
            name='prix_calcule',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avis',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.hotel'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='note',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='numero_chambre',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='prix_base_nuit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='type_chambre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.typechambre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disponibilite',
            name='chambre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.chambre'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='equipements',
            field=models.TextField(help_text='Séparés par des virgules'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='hotels/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='ville',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='chambre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.chambre'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut_paiement',
            field=models.CharField(default='En attente', max_length=50),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='chambre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.chambre'),
        ),
        migrations.AlterField(
            model_name='typechambre',
            name='libelle',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='prix_applique',
        ),
    ]
